# Generated by Django 3.2.5 on 2021-07-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Dan Brown', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='imageUrl',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.URLField(max_length=500),
        ),
    ]
